### ISSUE TITLE
Wrong Link in Sonarqube Description

### ISSUE THREAD

**Issue by triplem** [detekt/sonar-detekt#138]
In the Code-Smell Description in Sonarqube the old Website is still used (eg. https://arturbosch.github.io/detekt/style.html#wildcardimport). Could this be somehow updated? 
A workaround would be a redirect on the old page.

**Comment by cortinico** [comment]
> In the Code-Smell Description in Sonarqube the old Website is still used

Can you link it? Or post a screenshot?
I wasn't able to find out where the Code-Smell Description is.

**Comment by arturbosch** [comment]
It could be that official sonar-kotlin linked to the old url.
