### ISSUE TITLE
Is sonar-kotlin plugin compatible with Sonarqube EE 9.4?

### ISSUE THREAD

**Issue by shafemoh** [detekt/sonar-detekt#157]
Hi team,
we are currently hosting Sonarqube EE 9.2.4 and we will be upgrading to Sonarqube 9.4.0. We are currently using [sonar-detekt-2.4.0.jar](https://github.com/detekt/sonar-kotlin/releases/download/2.4.0/sonar-detekt-2.4.0.jar).
Should we upgrade the sonar-kotlin plugin to some higher version (if so, to which version ? )
OR Can we stay on [sonar-detekt-2.4.0.jar](https://github.com/detekt/sonar-kotlin/releases/download/2.4.0/sonar-detekt-2.4.0.jar)?

Regards @shafemoh

**Comment by cortinico** [comment]
> Should we upgrade the sonar-kotlin plugin to some higher version (if so, to which version ? )

Have you tested it against version 2.5.0?

**Comment by shafemoh** [comment]
Hi @cortinico Not yet. :)

**Comment by shafemoh** [comment]
Hi @cortinico Not yet. :) Do you have any compatibility matrix for this plugin?

**Comment by cortinico** [comment]
> Do you have any compatibility matrix for this plugin?

Sadly, not really.

**Comment by arturbosch** [comment]
@shafemoh I've tested https://github.com/detekt/sonar-detekt/releases/tag/2.6.0-RC1 with Sonarqube 9.9 LTS.
Feel free to give it a go.
