### ISSUE TITLE
How can I detect vulnerabilities and bugs

### ISSUE THREAD

**Issue by danielriverolosa** [detekt/sonar-detekt#68]
The default detekt way, only detects code smells, I'm not sure how and where I have to configure the detekt.yml file to improve the analysis, should I host it in the project, or where I have Sonar hosted? I don't quite understand what I have to do....

**Comment by arturbosch** [comment]
In the administration windows you can point to the detekt.yml. The property accepts aboslute paths (hosting the detekt.yml on the server side) or relative paths inside your project. Hope that helps!
